name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/cache@v4
      with:
        path: |
          ~/.cache/go/build
          ~/.cache/go/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

    - uses: cachix/install-nix-action@v30
      with:
        nix_path: nixpkgs=channel:nixos-stable

    - name: Build (CGO enabled)
      run: nix develop --accept-flake-config --command bash -lc 'CGO_ENABLED=1 go build ./...'

    - name: Test (race + parallel)
      run: nix develop --accept-flake-config --command bash -lc 'CGO_ENABLED=1 go test -race -count=1 -timeout=5m -p 4 -parallel 8 -run "." ./...'

    - name: Lint
      run: nix develop --accept-flake-config --command bash -lc 'golangci-lint run --timeout=5m'
